# Generated by Django 5.0.4 on 2024-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
    ]
